import { afterEach, beforeEach, expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';

const script = fileURLToPath(new URL('./version.mjs', import.meta.url));
const files = ['package.json', 'package-lock.json', 'src-tauri/Cargo.toml', 'src-tauri/Cargo.lock', 'src-tauri/tauri.conf.json'];
let root;
const read = path => readFileSync(join(root, path), 'utf8');
const write = (path, text) => writeFileSync(join(root, path), text);
const json = path => JSON.parse(read(path));
const writeJSON = (path, value) => write(path, JSON.stringify(value, null, 2) + '\n');
const git = (...args) => execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
const run = (args, env = {}) => spawnSync(process.execPath, [script, ...args], {
  cwd: root, encoding: 'utf8', env: { ...process.env, GITHUB_REF_TYPE: '', GITHUB_REF_NAME: '', ...env },
});
const commit = () => { git('add', '.'); git('commit', '-m', 'fixture'); };

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'dryad-version-'));
  mkdirSync(join(root, 'src-tauri'));
  writeJSON('package.json', { name: 'dryad', version: '0.2.0', private: true });
  writeJSON('package-lock.json', {
    name: 'dryad', version: '0.2.0', lockfileVersion: 3,
    packages: { '': { name: 'dryad', version: '0.2.0' }, 'node_modules/example': { version: '0.2.0' } },
  });
  write('src-tauri/Cargo.toml', '[package]\nname = "dryad"\nversion = "0.2.0" # app\n\n[dependencies]\nexample = { version = "0.2.0" }\n');
  write('src-tauri/Cargo.lock', '# Generated by Cargo\nversion = 4\n\n[[package]]\nname = "dryad"\nversion = "0.2.0"\n\n[[package]]\nname = "example"\nversion = "0.2.0"\n');
  writeJSON('src-tauri/tauri.conf.json', { version: '../package.json' });
  git('init');
  git('config', 'user.name', 'Version Test');
  git('config', 'user.email', 'version-test@example.invalid');
  git('config', 'commit.gpgSign', 'false');
  git('config', 'tag.gpgSign', 'false');
  git('config', 'core.hooksPath', join(root, 'no-hooks'));
  commit();
});

afterEach(() => rmSync(root, { recursive: true, force: true }));

it('synchronizes app versions without changing dependency versions, committing, or tagging', () => {
  const head = git('rev-parse', 'HEAD');
  const cargo = read('src-tauri/Cargo.toml');
  const lock = read('src-tauri/Cargo.lock');
  expect(run(['set', '0.3.0']).status).toBe(0);
  expect(json('package.json')).toEqual({ name: 'dryad', version: '0.3.0', private: true });
  expect(json('package-lock.json').version).toBe('0.3.0');
  expect(json('package-lock.json').packages[''].version).toBe('0.3.0');
  expect(json('package-lock.json').packages['node_modules/example'].version).toBe('0.2.0');
  expect(read('src-tauri/Cargo.toml')).toBe(cargo.replace('version = "0.2.0" # app', 'version = "0.3.0" # app'));
  expect(read('src-tauri/Cargo.lock')).toBe(lock.replace('name = "dryad"\nversion = "0.2.0"', 'name = "dryad"\nversion = "0.3.0"'));
  expect(run(['check']).status).toBe(0);
  expect(git('rev-parse', 'HEAD')).toBe(head);
  expect(git('tag', '--list')).toBe('');
});

it('checks the triggering CI tag while allowing development after an older tag', () => {
  git('tag', 'v0.1.0');
  const before = files.map(read);
  expect(run(['check']).status).toBe(0);
  expect(run(['check'], { GITHUB_REF_TYPE: 'branch', GITHUB_REF_NAME: 'master' }).status).toBe(0);
  expect(run(['check'], { GITHUB_REF_TYPE: 'tag', GITHUB_REF_NAME: 'v0.2.0' }).status).toBe(0);
  for (const tag of ['v0.3.0', '0.2.0', 'v0.2.0-extra', '']) {
    const result = run(['check'], { GITHUB_REF_TYPE: 'tag', GITHUB_REF_NAME: tag });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain('expected v0.2.0');
  }
  expect(files.map(read)).toEqual(before);
});

it.each([
  ['package-lock.json', text => text.replace('"version": "0.2.0"', '"version": "0.1.0"')],
  ['package-lock.json', text => text.replace('      "version": "0.2.0"', '      "version": "0.1.0"')],
  ['src-tauri/Cargo.toml', text => text.replace('version = "0.2.0" # app', 'version = "0.1.0" # app')],
  ['src-tauri/Cargo.lock', text => text.replace('name = "dryad"\nversion = "0.2.0"', 'name = "dryad"\nversion = "0.1.0"')],
  ['src-tauri/tauri.conf.json', text => text.replace('../package.json', '0.2.0')],
])('rejects drift in %s before tagging', (path, drift) => {
  write(path, drift(read(path)));
  commit();
  for (const command of ['check', 'tag']) {
    const result = run([command]);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(path);
  }
  expect(git('tag', '--list')).toBe('');
});

it.each(['v0.3.0', '01.3.0', '0.3', '0.3.0-beta.1', '0.3.0+build', '-1.0.0'])('rejects unsupported version %s without writes', version => {
  const before = files.map(read);
  const result = run(['set', version]);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('X.Y.Z');
  expect(files.map(read)).toEqual(before);
});

it.each([[], ['set'], ['set', '0.3.0', 'extra'], ['check', 'extra'], ['tag', 'v0.3.0']])('rejects invalid arguments %j', (...args) => {
  const result = run(args);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('Usage:');
  expect(git('status', '--porcelain')).toBe('');
});

it('preflights all files before synchronization writes', () => {
  write('src-tauri/Cargo.lock', read('src-tauri/Cargo.lock').replace('name = "dryad"', 'name = "missing"'));
  const before = files.map(read);
  const result = run(['set', '0.3.0']);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('src-tauri/Cargo.lock');
  expect(files.map(read)).toEqual(before);
  expect(git('tag', '--list')).toBe('');
});

it.each(['tracked', 'staged', 'untracked'])('refuses tagging with %s changes', kind => {
  write(kind === 'untracked' ? 'new.txt' : 'package.json', kind === 'untracked' ? 'new\n' : read('package.json') + '\n');
  if (kind === 'staged') git('add', 'package.json');
  const result = run(['tag']);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('clean');
  expect(git('tag', '--list')).toBe('');
});

it('creates an annotated tag for the current commit and refuses to replace it', () => {
  const head = git('rev-parse', 'HEAD');
  expect(run(['tag']).status).toBe(0);
  expect(git('cat-file', '-t', 'v0.2.0')).toBe('tag');
  expect(git('rev-parse', 'v0.2.0^{commit}')).toBe(head);
  expect(git('status', '--porcelain')).toBe('');
  const tagObject = git('rev-parse', 'v0.2.0');
  const result = run(['tag']);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('already exists');
  expect(git('rev-parse', 'v0.2.0')).toBe(tagObject);
});
